/* ===========================================
   Mock Data: Products (60 books across 5 categories)
   =========================================== */
window.MOCK_PRODUCTS = [
    // ===== FICTION (category_id: 1, product_id: 1-12) =====
    { product_id: 1, category_id: 1, category_name: "Fiction", product_name: "The Great Gatsby", author: "F. Scott Fitzgerald", product_price: 18.00, product_images: ["fiction-01.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan, set in the Jazz Age on Long Island." },
    { product_id: 2, category_id: 1, category_name: "Fiction", product_name: "To Kill a Mockingbird", author: "Harper Lee", product_price: 21.00, product_images: ["fiction-02.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A gripping tale of racial injustice in the Deep South, seen through the eyes of young Scout Finch." },
    { product_id: 3, category_id: 1, category_name: "Fiction", product_name: "1984", author: "George Orwell", product_price: 15.00, product_images: ["fiction-03.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A dystopian novel set in a totalitarian society ruled by Big Brother, exploring themes of surveillance and control." },
    { product_id: 4, category_id: 1, category_name: "Fiction", product_name: "Pride and Prejudice", author: "Jane Austen", product_price: 19.00, product_images: ["fiction-04.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The classic romance between Elizabeth Bennet and the proud Mr. Darcy in Regency-era England." },
    { product_id: 5, category_id: 1, category_name: "Fiction", product_name: "The Catcher in the Rye", author: "J.D. Salinger", product_price: 22.00, product_images: ["fiction-05.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The story of Holden Caulfield, a teenage boy navigating the complexities of growing up in New York City." },
    { product_id: 6, category_id: 1, category_name: "Fiction", product_name: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", product_price: 17.00, product_images: ["fiction-06.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The multi-generational story of the Buendia family in the fictional town of Macondo." },
    { product_id: 7, category_id: 1, category_name: "Fiction", product_name: "Brave New World", author: "Aldous Huxley", product_price: 20.00, product_images: ["fiction-07.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A futuristic society where humans are genetically modified and socially conditioned to serve a ruling order." },
    { product_id: 8, category_id: 1, category_name: "Fiction", product_name: "The Alchemist", author: "Paulo Coelho", product_price: 24.00, product_images: ["fiction-08.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A shepherd boy travels from Spain to Egypt in search of treasure, discovering the meaning of life along the way." },
    { product_id: 9, category_id: 1, category_name: "Fiction", product_name: "Norwegian Wood", author: "Haruki Murakami", product_price: 18.50, product_images: ["fiction-09.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A nostalgic story of loss and sexuality set in 1960s Tokyo, following Toru Watanabe's college years." },
    { product_id: 10, category_id: 1, category_name: "Fiction", product_name: "The Book Thief", author: "Markus Zusak", product_price: 19.99, product_images: ["fiction-10.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Narrated by Death, this is the story of Liesel Meminger, a girl living in Nazi Germany who steals books." },
    { product_id: 11, category_id: 1, category_name: "Fiction", product_name: "The Kite Runner", author: "Khaled Hosseini", product_price: 23.00, product_images: ["fiction-11.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A haunting tale of friendship between two boys growing up in Kabul, torn apart by war and betrayal." },
    { product_id: 12, category_id: 1, category_name: "Fiction", product_name: "Kafka on the Shore", author: "Haruki Murakami", product_price: 16.50, product_images: ["fiction-12.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A metaphysical journey following a teenage runaway and an old man who can talk to cats." },

    // ===== CHILDREN (category_id: 2, product_id: 13-24) =====
    { product_id: 13, category_id: 2, category_name: "Children", product_name: "Charlotte's Web", author: "E.B. White", product_price: 18.00, product_images: ["children-01.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The heartwarming story of a pig named Wilbur and his friendship with a spider named Charlotte." },
    { product_id: 14, category_id: 2, category_name: "Children", product_name: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling", product_price: 21.00, product_images: ["children-02.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A young orphan discovers he is a wizard and begins his magical education at Hogwarts School." },
    { product_id: 15, category_id: 2, category_name: "Children", product_name: "The Little Prince", author: "Antoine de Saint-Exupery", product_price: 15.00, product_images: ["children-03.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A pilot stranded in the desert meets a young prince who tells of his travels across the universe." },
    { product_id: 16, category_id: 2, category_name: "Children", product_name: "Matilda", author: "Roald Dahl", product_price: 19.00, product_images: ["children-04.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A brilliant young girl with telekinetic powers stands up to her neglectful parents and cruel headmistress." },
    { product_id: 17, category_id: 2, category_name: "Children", product_name: "The Chronicles of Narnia", author: "C.S. Lewis", product_price: 22.00, product_images: ["children-05.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Four siblings discover a magical wardrobe that leads to the enchanted land of Narnia." },
    { product_id: 18, category_id: 2, category_name: "Children", product_name: "Charlie and the Chocolate Factory", author: "Roald Dahl", product_price: 17.00, product_images: ["children-06.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Young Charlie Bucket wins a golden ticket to visit Willy Wonka's extraordinary chocolate factory." },
    { product_id: 19, category_id: 2, category_name: "Children", product_name: "The Giving Tree", author: "Shel Silverstein", product_price: 20.00, product_images: ["children-07.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A touching story about a tree that gives everything it has to a boy it loves throughout his life." },
    { product_id: 20, category_id: 2, category_name: "Children", product_name: "Where the Wild Things Are", author: "Maurice Sendak", product_price: 24.00, product_images: ["children-08.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Max sails away to an island inhabited by wild creatures and becomes king of all wild things." },
    { product_id: 21, category_id: 2, category_name: "Children", product_name: "Goodnight Moon", author: "Margaret Wise Brown", product_price: 18.50, product_images: ["children-09.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A beloved bedtime story where a young bunny says goodnight to everything in the great green room." },
    { product_id: 22, category_id: 2, category_name: "Children", product_name: "The Very Hungry Caterpillar", author: "Eric Carle", product_price: 19.99, product_images: ["children-10.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Follow a caterpillar as it eats its way through a variety of foods before transforming into a butterfly." },
    { product_id: 23, category_id: 2, category_name: "Children", product_name: "Green Eggs and Ham", author: "Dr. Seuss", product_price: 23.00, product_images: ["children-11.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Sam-I-Am tries to convince a grumpy character to try green eggs and ham in this classic rhyming tale." },
    { product_id: 24, category_id: 2, category_name: "Children", product_name: "The Cat in the Hat", author: "Dr. Seuss", product_price: 16.50, product_images: ["children-12.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Two bored children are visited by a tall, mischievous cat who turns their house into a playground." },

    // ===== NON-FICTION (category_id: 3, product_id: 25-36) =====
    { product_id: 25, category_id: 3, category_name: "Non-Fiction", product_name: "Sapiens: A Brief History", author: "Yuval Noah Harari", product_price: 18.00, product_images: ["nonfiction-01.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "An exploration of how Homo sapiens came to dominate the earth through cognitive, agricultural, and scientific revolutions." },
    { product_id: 26, category_id: 3, category_name: "Non-Fiction", product_name: "Educated", author: "Tara Westover", product_price: 21.00, product_images: ["nonfiction-02.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A memoir about growing up in a survivalist family in Idaho and the transformative power of education." },
    { product_id: 27, category_id: 3, category_name: "Non-Fiction", product_name: "Atomic Habits", author: "James Clear", product_price: 15.00, product_images: ["nonfiction-03.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A proven framework for building good habits and breaking bad ones through tiny, incremental changes." },
    { product_id: 28, category_id: 3, category_name: "Non-Fiction", product_name: "Thinking, Fast and Slow", author: "Daniel Kahneman", product_price: 19.00, product_images: ["nonfiction-04.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Nobel laureate explores the two systems that drive the way we think: fast intuition and slow deliberation." },
    { product_id: 29, category_id: 3, category_name: "Non-Fiction", product_name: "Becoming", author: "Michelle Obama", product_price: 22.00, product_images: ["nonfiction-05.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The former First Lady shares her journey from the South Side of Chicago to the White House." },
    { product_id: 30, category_id: 3, category_name: "Non-Fiction", product_name: "The Power of Now", author: "Eckhart Tolle", product_price: 17.00, product_images: ["nonfiction-06.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A guide to spiritual enlightenment that emphasizes the importance of living in the present moment." },
    { product_id: 31, category_id: 3, category_name: "Non-Fiction", product_name: "Quiet: The Power of Introverts", author: "Susan Cain", product_price: 20.00, product_images: ["nonfiction-07.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "How introverts are dramatically undervalued in a world that prizes extroversion, and the power of silence." },
    { product_id: 32, category_id: 3, category_name: "Non-Fiction", product_name: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", product_price: 24.00, product_images: ["nonfiction-08.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A counterintuitive approach to living a good life by choosing what matters and letting go of the rest." },
    { product_id: 33, category_id: 3, category_name: "Non-Fiction", product_name: "Outliers", author: "Malcolm Gladwell", product_price: 18.50, product_images: ["nonfiction-09.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "An investigation into what makes high achievers different, revealing the role of culture, timing, and opportunity." },
    { product_id: 34, category_id: 3, category_name: "Non-Fiction", product_name: "Freakonomics", author: "Steven Levitt", product_price: 19.99, product_images: ["nonfiction-10.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A rogue economist explores the hidden side of everything using data-driven analysis of everyday life." },
    { product_id: 35, category_id: 3, category_name: "Non-Fiction", product_name: "Man's Search for Meaning", author: "Viktor Frankl", product_price: 23.00, product_images: ["nonfiction-11.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A Holocaust survivor reflects on finding purpose and meaning even in the most horrific circumstances." },
    { product_id: 36, category_id: 3, category_name: "Non-Fiction", product_name: "Guns, Germs, and Steel", author: "Jared Diamond", product_price: 16.50, product_images: ["nonfiction-12.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Why did some civilizations conquer others? A groundbreaking look at geography, biology, and human history." },

    // ===== MYSTERY & THRILLER (category_id: 4, product_id: 37-48) =====
    { product_id: 37, category_id: 4, category_name: "Mystery & Thriller", product_name: "Gone Girl", author: "Gillian Flynn", product_price: 18.00, product_images: ["mt-01.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A husband becomes the prime suspect when his wife disappears on their fifth anniversary." },
    { product_id: 38, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", product_price: 21.00, product_images: ["mt-02.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A journalist and a hacker investigate a wealthy family's dark secrets spanning decades of corruption." },
    { product_id: 39, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Da Vinci Code", author: "Dan Brown", product_price: 15.00, product_images: ["mt-03.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A symbologist uncovers a religious mystery hidden in the works of Leonardo da Vinci." },
    { product_id: 40, category_id: 4, category_name: "Mystery & Thriller", product_name: "And Then There Were None", author: "Agatha Christie", product_price: 19.00, product_images: ["mt-04.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Ten strangers are lured to an island where they are accused of murder and begin to die one by one." },
    { product_id: 41, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Silent Patient", author: "Alex Michaelides", product_price: 22.00, product_images: ["mt-05.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A woman shoots her husband and then never speaks another word. A therapist is determined to uncover why." },
    { product_id: 42, category_id: 4, category_name: "Mystery & Thriller", product_name: "In the Woods", author: "Tana French", product_price: 17.00, product_images: ["mt-06.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A detective investigates a child's murder in the same woods where his childhood friends vanished twenty years ago." },
    { product_id: 43, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Girl on the Train", author: "Paula Hawkins", product_price: 20.00, product_images: ["mt-07.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A woman becomes entangled in a missing persons investigation that unravels her own troubled past." },
    { product_id: 44, category_id: 4, category_name: "Mystery & Thriller", product_name: "Sharp Objects", author: "Gillian Flynn", product_price: 24.00, product_images: ["mt-08.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A reporter returns to her hometown to cover the murders of two young girls and confronts her own demons." },
    { product_id: 45, category_id: 4, category_name: "Mystery & Thriller", product_name: "Big Little Lies", author: "Liane Moriarty", product_price: 18.50, product_images: ["mt-09.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Three women's seemingly perfect lives unravel to a breaking point at a school trivia night." },
    { product_id: 46, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Woman in the Window", author: "A.J. Finn", product_price: 19.99, product_images: ["mt-10.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "An agoraphobic woman believes she witnessed a crime in the apartment across the street." },
    { product_id: 47, category_id: 4, category_name: "Mystery & Thriller", product_name: "Murder on the Orient Express", author: "Agatha Christie", product_price: 23.00, product_images: ["mt-11.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Detective Hercule Poirot must solve a murder aboard a luxury train stranded in the snow." },
    { product_id: 48, category_id: 4, category_name: "Mystery & Thriller", product_name: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", product_price: 16.50, product_images: ["mt-12.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "Sherlock Holmes investigates the legend of a supernatural hound haunting a family on the Devon moors." },

    // ===== SCIENCE & TECHNOLOGY (category_id: 5, product_id: 49-60) =====
    { product_id: 49, category_id: 5, category_name: "Science & Technology", product_name: "A Brief History of Time", author: "Stephen Hawking", product_price: 18.00, product_images: ["sci-tech-01.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "From the Big Bang to black holes, Hawking explores the universe's deepest mysteries for the general reader." },
    { product_id: 50, category_id: 5, category_name: "Science & Technology", product_name: "The Innovators", author: "Walter Isaacson", product_price: 21.00, product_images: ["sci-tech-02.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The story of the pioneers who created the computer and the internet, from Ada Lovelace to Steve Jobs." },
    { product_id: 51, category_id: 5, category_name: "Science & Technology", product_name: "Cosmos", author: "Carl Sagan", product_price: 15.00, product_images: ["sci-tech-03.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A journey through the universe exploring the evolution of galaxies, stars, life, and human civilization." },
    { product_id: 52, category_id: 5, category_name: "Science & Technology", product_name: "The Gene: An Intimate History", author: "Siddhartha Mukherjee", product_price: 19.00, product_images: ["sci-tech-04.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A riveting history of the gene and a vision of both its promise and dangers for humanity's future." },
    { product_id: 53, category_id: 5, category_name: "Science & Technology", product_name: "Clean Code", author: "Robert C. Martin", product_price: 22.00, product_images: ["sci-tech-05.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A handbook of agile software craftsmanship with practical advice for writing clean, readable code." },
    { product_id: 54, category_id: 5, category_name: "Science & Technology", product_name: "The Structure of Scientific Revolutions", author: "Thomas S. Kuhn", product_price: 17.00, product_images: ["sci-tech-06.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A groundbreaking analysis of the history of science that introduced the concept of paradigm shifts." },
    { product_id: 55, category_id: 5, category_name: "Science & Technology", product_name: "Astrophysics for People in a Hurry", author: "Neil deGrasse Tyson", product_price: 20.00, product_images: ["sci-tech-07.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A concise guide to the universe's greatest mysteries, from dark matter to the cosmic microwave background." },
    { product_id: 56, category_id: 5, category_name: "Science & Technology", product_name: "Steve Jobs", author: "Walter Isaacson", product_price: 24.00, product_images: ["sci-tech-08.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The definitive biography of Apple's co-founder, based on exclusive interviews with Jobs and those closest to him." },
    { product_id: 57, category_id: 5, category_name: "Science & Technology", product_name: "The Selfish Gene", author: "Richard Dawkins", product_price: 18.50, product_images: ["sci-tech-09.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "A revolutionary look at evolution centered on the gene as the fundamental unit of natural selection." },
    { product_id: 58, category_id: 5, category_name: "Science & Technology", product_name: "Elon Musk", author: "Ashlee Vance", product_price: 19.99, product_images: ["sci-tech-10.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The biography of the entrepreneur behind Tesla, SpaceX, and the quest to colonize Mars." },
    { product_id: 59, category_id: 5, category_name: "Science & Technology", product_name: "The Code Book", author: "Simon Singh", product_price: 23.00, product_images: ["sci-tech-11.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "The history of cryptography from ancient Egypt to quantum computing and the science of secrecy." },
    { product_id: 60, category_id: 5, category_name: "Science & Technology", product_name: "Algorithms to Live By", author: "Brian Christian", product_price: 16.50, product_images: ["sci-tech-12.png"], product_attributes: { format: ["Paperback", "Hardcover", "E-Book"] }, product_description: "How computer algorithms can help solve everyday human problems from organizing to decision-making." }
];
